### ISSUE TITLE
PhantomJS support?

### ISSUE THREAD

**Issue by Jaymon** [Jaymon/wishlist#1]
http://stackoverflow.com/questions/13287490/is-there-a-way-to-use-phantomjs-in-python/15699761#15699761

Looks like something in Selenium, xvfb, and Spam Assassin doesn't play well together, phantomJS should eliminate the xvfb part and hopefully that's the part that has problems with SA

It's not the browser, because I've tried both Firefox and Chrome. It's a weird enough freeze where I have to cycle the box, and that feels like something xvfb would be the cause of.

**Comment by jantman** [comment]
I haven't used xvfb in a long time, but yes, I noticed strange behavior on some platforms when using it. I'd give phantomjs a try.

**Comment by Jaymon** [comment]
With headless support in both Firefox and Chrome the [PhantomJS guy stepped down](https://groups.google.com/d/msg/phantomjs/9aI5d-LDuNE/5Z3SMZrqAQAJ) so this doesn't seem relevant anymore
