### ISSUE TITLE
Check for Firefox and Chrome

### ISSUE THREAD

**Issue by Jaymon** [Jaymon/wishlist#2]
since I've switched the actual list parsing to use requests, there's no reason to go through the trouble of installing Chrome if you don't need it, so this should maybe check for Chrome, if that's not there, check for Firefox, if that isn't found, go for phantomJS?

**Comment by jantman** [comment]
For what it's worth, I think the user should be able to choose which browser they want to use. I almost continued right past this project in my search for a wishlist parser, when I saw that it required xvfb...

**Comment by Jaymon** [comment]
a lot of the code was written before Firefox and Chrome had headless support.

I'm also not sure it works at all anymore since Amazon rolled out a wishlist update that switches to a javascript load more, I think I've worked through how to make it work with the new stuff but haven't had the time to attempt an update yet.

Basically, I need to update the browser stuff to use either browser in headless mode, and then fix the actual list parsing

**Comment by jantman** [comment]
Ah, ok, thanks for the update. My longest wishlist only has 21 items, and it's currently working fine for that one.
