### ISSUE TITLE
look into running the browser from docker container

### ISSUE THREAD

**Issue by Jaymon** [Jaymon/wishlist#5]
is this possible? I want to do some research to see if this would be a viable way to avoid all the dependencies for the browser if there was a container that had them ready to go and this could just plug into it.

**Comment by jantman** [comment]
Yeah, that's possible. Selenium just uses the webdriver protocol, so you could have a Docker container running whatever browser, and just connect to the proper port...

**Comment by Jaymon** [comment]
With headless options available for both Chrome and Firefox and the selenium part of this being moved into [Brow](https://github.com/Jaymon/brow) I'm closing this as not relevant anymore
